version: "3.9"
services:
  protected-resource-csharp:
    build: .
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
      ASPNETCORE_URLS: "http://+;https://+"
      Auth__BaseUrl: "http://auth:80"
    ports:
      - "20030:443"
    volumes:
      - /Users/dk/.aspnet/https/localhost.pfx:/https/localhost.pfx